### ISSUE TITLE
Performance when adding collections / fields

### ISSUE THREAD

**Issue by CoenWarmer** [directus/next#518]
We are evaluating Directus 9, and when creating a collection and adding a few fields we are experiencing very slow performance (> 7 seconds, 20.25 s max) when accessing endpoints related to collection creation.

I've installed Directus 9 beta 8 with `npx create-directus-project my-project`, then started it with `npx directus start`. We're using a Postgres DB that's running in a docker container via a docker-compose file. It is newly created for this purpose.

Docker-compose file:

```
version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
```

<img width="633" alt="Screenshot 2020-10-05 at 13 28 58" src="https://user-images.githubusercontent.com/535564/95075790-14d0d180-0711-11eb-8b18-bcada7a67cf1.png">
<img width="634" alt="Screenshot 2020-10-05 at 13 28 50" src="https://user-images.githubusercontent.com/535564/95075795-17332b80-0711-11eb-9f73-0053954a9c65.png">
<img width="631" alt="Screenshot 2020-10-05 at 13 28 45" src="https://user-images.githubusercontent.com/535564/95075799-17cbc200-0711-11eb-91e0-8383ff0cbeda.png">
<img width="631" alt="Screenshot 2020-10-05 at 13 28 39" src="https://user-images.githubusercontent.com/535564/95075800-18645880-0711-11eb-9707-2d5e74170873.png">

Is this expected as part of the beta or are we misconfiguring something on our end?
