### ISSUE TITLE
[MSSQL] Database is not created at first start

### ISSUE THREAD

**Issue by mscbpi** [directus/next#665]
Running v9.0.0beta11 docker image. Azure MS SQL Instance:

Pre-requisite: DB is created, empty, and the user is admin owner on the DB

ENV:
```
      - env:
        - name: DB_CLIENT
          value: mssql
        - name: DB_DATABASE
          value: directus
        - name: DB_HOST
          value: <myhost>.database.windows.net
        - name: DB_PASSWORD
          value: <mypassword>
        - name: DB_PORT
          value: "1433"
        - name: DB_USER
          value: <myuser>
        - name: DIRECTUS_ADMIN_EMAIL
          value: <myemail>
        - name: DIRECTUS_ADMIN_PASSWORD
          value: <directuspassword>
        - name: PORT
          value: "80"
```

At boot:

```
node:1) UnhandledPromiseRejectionWarning: RequestError: select * from [directus_webhooks] where [status] = @p0 - Invalid object name 'directus_webhooks'.
    at handleError (/directus/node_modules/mssql/lib/tedious/request.js:366:15)
    at Connection.emit (events.js:314:20)
    at Parser.<anonymous> (/directus/node_modules/tedious/lib/connection.js:832:12)
    at Parser.emit (events.js:314:20)
    at Parser.<anonymous> (/directus/node_modules/tedious/lib/token/token-stream-parser.js:37:14)
    at Parser.emit (events.js:314:20)
    at addChunk (/directus/node_modules/tedious/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/directus/node_modules/tedious/node_modules/readable-stream/lib/_stream_readable.js:280:11)
    at Parser.Readable.push (/directus/node_modules/tedious/node_modules/readable-stream/lib/_stream_readable.js:241:10)
    at Parser.Transform.push (/directus/node_modules/tedious/node_modules/readable-stream/lib/_stream_transform.js:139:32)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

When trying to logging in, among others:

```
08:10:42 🚨 RequestError select top (@p0) [id], [password], [role], [tfa_secret], [status] from [directus_users] where [email] = @p1 - Invalid object name 'directus_users'.
```
