### ISSUE TITLE
Error on dockerise directus creating the database

### ISSUE THREAD

**Issue by juancarlosjr97** [directus/next#868]
Steps to reproduce:

1. Create a `docker-compose.yml`

```
version: "3"

networks:
  backend:

services:
  db:
    image: postgres
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - backend

  backend-directus:
    image: directus/next:v9.0.0-rc.5
    env_file: .env
    ports:
      - "8055:8055"
    networks:
      - backend

```

2. Create a .env

```
####################################################################################################
## Admin account

DIRECTUS_ADMIN_EMAIL="admin@local.com"
DIRECTUS_ADMIN_PASSWORD="pass"

####################################################################################################
## Database Credentials

POSTGRES_DB="directus-v9-local"
POSTGRES_USER="admin"
POSTGRES_PASSWORD="pass"

####################################################################################################
## General

PORT=8055
PUBLIC_URL="/"

####################################################################################################
## Database

DB_CLIENT="pg"
DB_HOST="host.docker.internal"
DB_PORT="5432"
DB_DATABASE="directus-v9-local"
DB_USER="admin"
DB_PASSWORD="pass"
DB_SSL="false"

####################################################################################################
## Rate Limiting

RATE_LIMITER_ENABLED=false
RATE_LIMITER_STORE=memory
RATE_LIMITER_POINTS=25
RATE_LIMITER_DURATION=1

####################################################################################################
## Cache

CACHE_ENABLED=false

####################################################################################################
## File Storage

STORAGE_LOCATIONS="local"
STORAGE_LOCAL_PUBLIC_URL="/uploads"
STORAGE_LOCAL_DRIVER="local"
STORAGE_LOCAL_ROOT="./uploads"

####################################################################################################
## Security

KEY="e891ab56-d5e2-4d92-b844-26098e62797b"
SECRET="E4OhqYHBFKZOv8tmFwiY7XODAsqM5Q7D"

ACCESS_TOKEN_TTL="15m"
REFRESH_TOKEN_TTL="7d"
REFRESH_TOKEN_COOKIE_SECURE=false
REFRESH_TOKEN_COOKIE_SAME_SITE="lax"

####################################################################################################
## SSO (OAuth) Providers

OAUTH_PROVIDERS=""

####################################################################################################
## Extensions

EXTENSIONS_PATH="./extensions"

####################################################################################################
## Email

EMAIL_FROM="no-reply@directus.io"
EMAIL_TRANSPORT="sendmail"
EMAIL_SENDMAIL_NEW_LINE="unix"
EMAIL_SENDMAIL_PATH="/usr/sbin/sendmail"

```

3. Run `docker-compose up`

This will return an error creating the database.

```
backend-directus_1  | (node:1) UnhandledPromiseRejectionWarning: error: select * from "directus_webhooks" where "status" = $1 - relation "directus_webhooks" does not exist
.
.
.
```

4. Run `docker-compose down` to turn off the containers
5. Run `docker-compose up` and will create the database and finish the installation of the clean Directus successfully
